######################################################################
# Automatically generated by qmake (1.07a) Mon Oct 12 12:38:31 2009
######################################################################

TEMPLATE = app
INCLUDEPATH += .

# Input
HEADERS += colorarray.h component.h displayer.h stroboarray.h
SOURCES += colorarray.cpp component.cpp displayer.cpp main.cpp stroboarray.cpp
