#############################################################################
# Makefile for building: luci
# Generated by qmake (1.07a) (Qt 3.3.8b) on: Mon Oct 12 12:38:32 2009
# Project:  luci.pro
# Template: app
# Command: $(QMAKE) -o Makefile luci.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
CXXFLAGS = -pipe -g -Wall -W -O2 -D_REENTRANT  -DQT_NO_DEBUG -DQT_THREAD_SUPPORT -DQT_SHARED -DQT_TABLET_SUPPORT
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I/usr/share/qt3/mkspecs/default -I. -I. -I/usr/include/qt3
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS) -L/usr/share/qt3/lib -L/usr/X11R6/lib -lqt-mt -lXext -lX11 -lm -lpthread
AR       = ar cqs
RANLIB   = 
MOC      = /usr/share/qt3/bin/moc
UIC      = /usr/share/qt3/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY)
COPY_DIR = $(COPY) -r
INSTALL_FILE= $(COPY_FILE)
INSTALL_DIR = $(COPY_DIR)
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = colorarray.h \
		component.h \
		displayer.h \
		stroboarray.h
SOURCES = colorarray.cpp \
		component.cpp \
		displayer.cpp \
		main.cpp \
		stroboarray.cpp
OBJECTS = colorarray.o \
		component.o \
		displayer.o \
		main.o \
		stroboarray.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_colorarray.cpp \
		moc_component.cpp \
		moc_displayer.cpp \
		moc_stroboarray.cpp
OBJMOC = moc_colorarray.o \
		moc_component.o \
		moc_displayer.o \
		moc_stroboarray.o
DIST	   = luci.pro
QMAKE_TARGET = luci
DESTDIR  = 
TARGET   = luci

first: all
####### Implicit rules

.SUFFIXES: .c .o .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(UICDECLS) $(OBJECTS) $(OBJMOC)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(OBJCOMP) $(LIBS)

mocables: $(SRCMOC)
uicables: $(UICDECLS) $(UICIMPLS)

$(MOC): 
	( cd $(QTDIR)/src/moc && $(MAKE) )

Makefile: luci.pro  /usr/share/qt3/mkspecs/default/qmake.conf /usr/share/qt3/lib/libqt-mt.prl
	$(QMAKE) -o Makefile luci.pro
qmake: 
	@$(QMAKE) -o Makefile luci.pro

dist: 
	@mkdir -p .tmp/luci && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/luci/ && ( cd `dirname .tmp/luci` && $(TAR) luci.tar luci && $(GZIP) luci.tar ) && $(MOVE) `dirname .tmp/luci`/luci.tar.gz . && $(DEL_FILE) -r .tmp/luci

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

yaccclean:
lexclean:
clean: mocclean
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

colorarray.o: colorarray.cpp colorarray.h \
		component.h

component.o: component.cpp component.h

displayer.o: displayer.cpp displayer.h

main.o: main.cpp colorarray.h \
		stroboarray.h \
		displayer.h

stroboarray.o: stroboarray.cpp stroboarray.h \
		component.h

moc_colorarray.o: moc_colorarray.cpp  colorarray.h 

moc_component.o: moc_component.cpp  component.h 

moc_displayer.o: moc_displayer.cpp  displayer.h 

moc_stroboarray.o: moc_stroboarray.cpp  stroboarray.h 

moc_colorarray.cpp: $(MOC) colorarray.h
	$(MOC) colorarray.h -o moc_colorarray.cpp

moc_component.cpp: $(MOC) component.h
	$(MOC) component.h -o moc_component.cpp

moc_displayer.cpp: $(MOC) displayer.h
	$(MOC) displayer.h -o moc_displayer.cpp

moc_stroboarray.cpp: $(MOC) stroboarray.h
	$(MOC) stroboarray.h -o moc_stroboarray.cpp

####### Install

install:  

uninstall:  

